name: hajimi
services:
  webui:
    build: .
    environment:
      - APP_MODE=webui
    ports:
      - "8501:8501"

  api:
    build: .
    environment:
      - APP_MODE=api
    ports:
      - "8000:8000"